// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dash-ui

#ifndef UI_DASH_H
#define UI_DASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dash
extern void ui_dash_screen_init(void);
extern void ui_dash_screen_destroy(void);
extern lv_obj_t * ui_dash;
extern lv_obj_t * ui_gearpanel;
extern lv_obj_t * ui_GEAR;
extern lv_obj_t * ui_MESSAGEPANEL;
extern lv_obj_t * ui_speedpanel;
extern lv_obj_t * ui_battpanel;
extern lv_obj_t * ui_temppanel;
extern lv_obj_t * ui_pressurepanel;
extern lv_obj_t * ui_HOTMESSAGE;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SPEEDMPH;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_BATTVOLTAGE;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_OILTEMP;
extern lv_obj_t * ui_COOLANTTEMP;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_OILPRESSURE;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_FUELPRESSURE;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_rpmbar;
extern lv_obj_t * ui_RPMVAL;
extern lv_obj_t * ui_LCMESSAGE;
// CUSTOM VARIABLES
extern lv_obj_t * uic_dash;
extern lv_obj_t * uic_gearpanel;
extern lv_obj_t * uic_GEAR;
extern lv_obj_t * uic_MESSAGEPANEL;
extern lv_obj_t * uic_speedpanel;
extern lv_obj_t * uic_battpanel;
extern lv_obj_t * uic_temppanel;
extern lv_obj_t * uic_pressurepanel;
extern lv_obj_t * uic_HOTMESSAGE;
extern lv_obj_t * uic_SPEEDMPH;
extern lv_obj_t * uic_BATTVOLTAGE;
extern lv_obj_t * uic_OILTEMP;
extern lv_obj_t * uic_COOLANTTEMP;
extern lv_obj_t * uic_OILPRESSURE;
extern lv_obj_t * uic_FUELPRESSURE;
extern lv_obj_t * uic_rpmbar;
extern lv_obj_t * uic_RPMVAL;
extern lv_obj_t * uic_LCMESSAGE;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

