// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dash-ui

#include "../ui.h"

lv_obj_t * uic_THROTTLEPOS;
lv_obj_t * uic_BATTVOLTAGE;
lv_obj_t * uic_MAPPRES;
lv_obj_t * uic_OILPRES;
lv_obj_t * uic_FUELPRES;
lv_obj_t * uic_AIRTEMP;
lv_obj_t * uic_COOLANTTEMP;
lv_obj_t * uic_OILTEMP;
lv_obj_t * uic_SPEEDMPH;
lv_obj_t * uic_LAPTIME;
lv_obj_t * uic_RPMVAL;
lv_obj_t * uic_MESSAGE;
lv_obj_t * uic_Panel9;
lv_obj_t * uic_Panel8;
lv_obj_t * uic_Panel7;
lv_obj_t * uic_Panel5;
lv_obj_t * uic_Panel4;
lv_obj_t * uic_Panel3;
lv_obj_t * uic_MESSAGEPANEL;
lv_obj_t * uic_GEAR;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_RPMBAR;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_RPMBAR = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_GEAR = NULL;
lv_obj_t * ui_MESSAGEPANEL = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_MESSAGE = NULL;
lv_obj_t * ui_RPMVAL = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_LAPTIME = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_SPEEDMPH = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_OILTEMP = NULL;
lv_obj_t * ui_COOLANTTEMP = NULL;
lv_obj_t * ui_AIRTEMP = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_FUELPRES = NULL;
lv_obj_t * ui_OILPRES = NULL;
lv_obj_t * ui_MAPPRES = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_BATTVOLTAGE = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_THROTTLEPOS = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x181719), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMBAR = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_RPMBAR, 0, 4096);
    lv_bar_set_value(ui_RPMBAR, 3000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RPMBAR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMBAR, 800);
    lv_obj_set_height(ui_RPMBAR, 29);
    lv_obj_set_x(ui_RPMBAR, 0);
    lv_obj_set_y(ui_RPMBAR, -225);
    lv_obj_set_align(ui_RPMBAR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RPMBAR, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_radius(ui_RPMBAR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBAR, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RPMBAR, &ui_img_rpmlightsgrey_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_RPMBAR, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMBAR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBAR, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBAR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RPMBAR, lv_color_hex(0xFA051A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RPMBAR, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RPMBAR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RPMBAR, &ui_img_rpmlights_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 210);
    lv_obj_set_height(ui_Panel1, 200);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -100);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Panel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GEAR = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GEAR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GEAR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GEAR, 0);
    lv_obj_set_y(ui_GEAR, -100);
    lv_obj_set_align(ui_GEAR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GEAR, "N");
    lv_obj_set_style_text_color(ui_GEAR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR, &ui_font_Montserrat_112, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MESSAGEPANEL = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MESSAGEPANEL, 210);
    lv_obj_set_height(ui_MESSAGEPANEL, 102);
    lv_obj_set_x(ui_MESSAGEPANEL, 0);
    lv_obj_set_y(ui_MESSAGEPANEL, 60);
    lv_obj_set_align(ui_MESSAGEPANEL, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MESSAGEPANEL, LV_STATE_USER_1);       /// States
    lv_obj_clear_flag(ui_MESSAGEPANEL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MESSAGEPANEL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MESSAGEPANEL, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MESSAGEPANEL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_MESSAGEPANEL, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MESSAGEPANEL, lv_color_hex(0xFA051A), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_MESSAGEPANEL, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 275);
    lv_obj_set_height(ui_Panel3, 135);
    lv_obj_set_x(ui_Panel3, -253);
    lv_obj_set_y(ui_Panel3, -133);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 275);
    lv_obj_set_height(ui_Panel4, 135);
    lv_obj_set_x(ui_Panel4, -253);
    lv_obj_set_y(ui_Panel4, 11);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 275);
    lv_obj_set_height(ui_Panel5, 135);
    lv_obj_set_x(ui_Panel5, -253);
    lv_obj_set_y(ui_Panel5, 156);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 210);
    lv_obj_set_height(ui_Panel6, 102);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 173);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 275);
    lv_obj_set_height(ui_Panel7, 135);
    lv_obj_set_x(ui_Panel7, 253);
    lv_obj_set_y(ui_Panel7, -133);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 275);
    lv_obj_set_height(ui_Panel8, 135);
    lv_obj_set_x(ui_Panel8, 253);
    lv_obj_set_y(ui_Panel8, 11);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 275);
    lv_obj_set_height(ui_Panel9, 135);
    lv_obj_set_x(ui_Panel9, 253);
    lv_obj_set_y(ui_Panel9, 156);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x27252C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MESSAGE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MESSAGE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MESSAGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MESSAGE, 0);
    lv_obj_set_y(ui_MESSAGE, 61);
    lv_obj_set_align(ui_MESSAGE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MESSAGE, "HOT");
    lv_obj_set_style_text_color(ui_MESSAGE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MESSAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MESSAGE, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMVAL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_RPMVAL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMVAL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMVAL, 253);
    lv_obj_set_y(ui_RPMVAL, -133);
    lv_obj_set_align(ui_RPMVAL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMVAL, "9000");
    lv_obj_set_style_text_color(ui_RPMVAL, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMVAL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMVAL, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 154);
    lv_obj_set_y(ui_Label4, -177);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "RPM");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LAPTIME = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LAPTIME, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LAPTIME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LAPTIME, 0);
    lv_obj_set_y(ui_LAPTIME, 173);
    lv_obj_set_align(ui_LAPTIME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LAPTIME, "1:12.01");
    lv_obj_set_style_text_font(ui_LAPTIME, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -343);
    lv_obj_set_y(ui_Label6, -178);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Speed ");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SPEEDMPH = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SPEEDMPH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SPEEDMPH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SPEEDMPH, -253);
    lv_obj_set_y(ui_SPEEDMPH, -133);
    lv_obj_set_align(ui_SPEEDMPH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SPEEDMPH, "30.1");
    lv_obj_set_style_text_color(ui_SPEEDMPH, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SPEEDMPH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SPEEDMPH, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -195);
    lv_obj_set_y(ui_Label8, -125);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "MPH");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -303);
    lv_obj_set_y(ui_Label9, 123);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Oil");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -328);
    lv_obj_set_y(ui_Label10, 154);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Coolant");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -304);
    lv_obj_set_y(ui_Label11, 185);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Air");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OILTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OILTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OILTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OILTEMP, -253);
    lv_obj_set_y(ui_OILTEMP, 121);
    lv_obj_set_align(ui_OILTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OILTEMP, "110");
    lv_obj_set_style_text_color(ui_OILTEMP, lv_color_hex(0xFA051A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OILTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OILTEMP, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_COOLANTTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_COOLANTTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_COOLANTTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_COOLANTTEMP, -254);
    lv_obj_set_y(ui_COOLANTTEMP, 153);
    lv_obj_set_align(ui_COOLANTTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_COOLANTTEMP, "83");
    lv_obj_set_style_text_color(ui_COOLANTTEMP, lv_color_hex(0xFB9B02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_COOLANTTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_COOLANTTEMP, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRTEMP = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AIRTEMP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIRTEMP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIRTEMP, -253);
    lv_obj_set_y(ui_AIRTEMP, 186);
    lv_obj_set_align(ui_AIRTEMP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIRTEMP, "37");
    lv_obj_set_style_text_color(ui_AIRTEMP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRTEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRTEMP, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -225);
    lv_obj_set_y(ui_Label15, 121);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "C");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -224);
    lv_obj_set_y(ui_Label16, 153);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "C");

    ui_Label17 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -224);
    lv_obj_set_y(ui_Label17, 186);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "C");

    ui_Label18 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 200);
    lv_obj_set_y(ui_Label18, 122);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Fuel");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 203);
    lv_obj_set_y(ui_Label19, 154);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Oil");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 196);
    lv_obj_set_y(ui_Label20, 188);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "MAP");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUELPRES = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FUELPRES, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUELPRES, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUELPRES, 253);
    lv_obj_set_y(ui_FUELPRES, 122);
    lv_obj_set_align(ui_FUELPRES, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FUELPRES, "42");
    lv_obj_set_style_text_color(ui_FUELPRES, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FUELPRES, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FUELPRES, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OILPRES = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OILPRES, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OILPRES, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OILPRES, 253);
    lv_obj_set_y(ui_OILPRES, 155);
    lv_obj_set_align(ui_OILPRES, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OILPRES, "53");
    lv_obj_set_style_text_color(ui_OILPRES, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OILPRES, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OILPRES, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAPPRES = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MAPPRES, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAPPRES, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAPPRES, 253);
    lv_obj_set_y(ui_MAPPRES, 187);
    lv_obj_set_align(ui_MAPPRES, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MAPPRES, "93");
    lv_obj_set_style_text_color(ui_MAPPRES, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MAPPRES, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MAPPRES, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 289);
    lv_obj_set_y(ui_Label24, 127);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "psi");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 289);
    lv_obj_set_y(ui_Label25, 157);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "psi");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 291);
    lv_obj_set_y(ui_Label26, 189);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "kPa");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 169);
    lv_obj_set_y(ui_Label27, -31);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Throttle");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -339);
    lv_obj_set_y(ui_Label28, -34);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Battery");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BATTVOLTAGE = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BATTVOLTAGE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BATTVOLTAGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BATTVOLTAGE, -253);
    lv_obj_set_y(ui_BATTVOLTAGE, 11);
    lv_obj_set_align(ui_BATTVOLTAGE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BATTVOLTAGE, "11.7");
    lv_obj_set_style_text_color(ui_BATTVOLTAGE, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BATTVOLTAGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BATTVOLTAGE, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -213);
    lv_obj_set_y(ui_Label30, 17);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "V");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_THROTTLEPOS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_THROTTLEPOS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_THROTTLEPOS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_THROTTLEPOS, 250);
    lv_obj_set_y(ui_THROTTLEPOS, 12);
    lv_obj_set_align(ui_THROTTLEPOS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_THROTTLEPOS, "12.0");
    lv_obj_set_style_text_font(ui_THROTTLEPOS, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, 299);
    lv_obj_set_y(ui_Label32, 17);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "%");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 327);
    lv_obj_set_y(ui_Label33, -129);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "RPM");
    lv_obj_set_style_text_color(ui_Label33, lv_color_hex(0xB1BECA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label33, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen1 = ui_Screen1;
    uic_RPMBAR = ui_RPMBAR;
    uic_Panel1 = ui_Panel1;
    uic_GEAR = ui_GEAR;
    uic_MESSAGEPANEL = ui_MESSAGEPANEL;
    uic_Panel3 = ui_Panel3;
    uic_Panel4 = ui_Panel4;
    uic_Panel5 = ui_Panel5;
    uic_Panel7 = ui_Panel7;
    uic_Panel8 = ui_Panel8;
    uic_Panel9 = ui_Panel9;
    uic_MESSAGE = ui_MESSAGE;
    uic_RPMVAL = ui_RPMVAL;
    uic_LAPTIME = ui_LAPTIME;
    uic_SPEEDMPH = ui_SPEEDMPH;
    uic_OILTEMP = ui_OILTEMP;
    uic_COOLANTTEMP = ui_COOLANTTEMP;
    uic_AIRTEMP = ui_AIRTEMP;
    uic_FUELPRES = ui_FUELPRES;
    uic_OILPRES = ui_OILPRES;
    uic_MAPPRES = ui_MAPPRES;
    uic_BATTVOLTAGE = ui_BATTVOLTAGE;
    uic_THROTTLEPOS = ui_THROTTLEPOS;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    uic_RPMBAR = NULL;
    ui_RPMBAR = NULL;
    uic_Panel1 = NULL;
    ui_Panel1 = NULL;
    uic_GEAR = NULL;
    ui_GEAR = NULL;
    uic_MESSAGEPANEL = NULL;
    ui_MESSAGEPANEL = NULL;
    uic_Panel3 = NULL;
    ui_Panel3 = NULL;
    uic_Panel4 = NULL;
    ui_Panel4 = NULL;
    uic_Panel5 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    uic_Panel7 = NULL;
    ui_Panel7 = NULL;
    uic_Panel8 = NULL;
    ui_Panel8 = NULL;
    uic_Panel9 = NULL;
    ui_Panel9 = NULL;
    uic_MESSAGE = NULL;
    ui_MESSAGE = NULL;
    uic_RPMVAL = NULL;
    ui_RPMVAL = NULL;
    ui_Label4 = NULL;
    uic_LAPTIME = NULL;
    ui_LAPTIME = NULL;
    ui_Label6 = NULL;
    uic_SPEEDMPH = NULL;
    ui_SPEEDMPH = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    uic_OILTEMP = NULL;
    ui_OILTEMP = NULL;
    uic_COOLANTTEMP = NULL;
    ui_COOLANTTEMP = NULL;
    uic_AIRTEMP = NULL;
    ui_AIRTEMP = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    uic_FUELPRES = NULL;
    ui_FUELPRES = NULL;
    uic_OILPRES = NULL;
    ui_OILPRES = NULL;
    uic_MAPPRES = NULL;
    ui_MAPPRES = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    uic_BATTVOLTAGE = NULL;
    ui_BATTVOLTAGE = NULL;
    ui_Label30 = NULL;
    uic_THROTTLEPOS = NULL;
    ui_THROTTLEPOS = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;

}
