// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dash-ui

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_RPMBAR;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_GEAR;
extern lv_obj_t * ui_MESSAGEPANEL;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_MESSAGE;
extern lv_obj_t * ui_RPMVAL;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_LAPTIME;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SPEEDMPH;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_OILTEMP;
extern lv_obj_t * ui_COOLANTTEMP;
extern lv_obj_t * ui_AIRTEMP;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_FUELPRES;
extern lv_obj_t * ui_OILPRES;
extern lv_obj_t * ui_MAPPRES;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_BATTVOLTAGE;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_THROTTLEPOS;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_RPMBAR;
extern lv_obj_t * uic_Panel1;
extern lv_obj_t * uic_GEAR;
extern lv_obj_t * uic_MESSAGEPANEL;
extern lv_obj_t * uic_Panel3;
extern lv_obj_t * uic_Panel4;
extern lv_obj_t * uic_Panel5;
extern lv_obj_t * uic_Panel7;
extern lv_obj_t * uic_Panel8;
extern lv_obj_t * uic_Panel9;
extern lv_obj_t * uic_MESSAGE;
extern lv_obj_t * uic_RPMVAL;
extern lv_obj_t * uic_LAPTIME;
extern lv_obj_t * uic_SPEEDMPH;
extern lv_obj_t * uic_OILTEMP;
extern lv_obj_t * uic_COOLANTTEMP;
extern lv_obj_t * uic_AIRTEMP;
extern lv_obj_t * uic_FUELPRES;
extern lv_obj_t * uic_OILPRES;
extern lv_obj_t * uic_MAPPRES;
extern lv_obj_t * uic_BATTVOLTAGE;
extern lv_obj_t * uic_THROTTLEPOS;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

