// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dash-ui

#ifndef UI_LOADING_H
#define UI_LOADING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_loading
extern void ui_loading_screen_init(void);
extern void ui_loading_screen_destroy(void);
extern lv_obj_t * ui_loading;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_loading;
extern lv_obj_t * uic_Image1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

