// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: dash-ui

#ifndef _DASH_UI_UI_H
#define _DASH_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rpmlightsgrey_png);    // assets/rpmlightsgrey.png
LV_IMG_DECLARE(ui_img_rpmlights_png);    // assets/rpmlights.png

// FONTS
LV_FONT_DECLARE(ui_font_Montserrat_112);
LV_FONT_DECLARE(ui_font_Montserrat_96);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
